version: '3.9'
services:
  api:
    build: .
    container_name: nestjs-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app            # sync local code for hot reload
    command: npm run start:dev

  db:
    image: postgres:15-alpine
    container_name: nestjs-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
